# Remove
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#server:
#  port: 8070

spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888

# Remove
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/schools
#    username: springbootmicroservices
#    password: springbootmicroservices
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#application:
#  config:
#    students-url: http://localhost:8090/api/v1/students

# -------------------------------------------------------

#spring:
#  application:
#    name: schools
#  config:
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:posgresql://localhost:5432/schools
#    username: username
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect