# We don't need to register it in Eureka
eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

# By default, it set to true
# Fetch the information from the discovery server
spring:
  application:
    name: gateway
  #    Fetch the information from Discovery server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

