eureka:
  client:
    register-with-eureka: false  # No need to register it in Eureka server

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Fetch the information about registered microservices from Discovery server
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

# Zipkin config
#management:
#  tracing:
#    sampling:
#      probability: 1.0

