eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090


spring:
  application:
    name: students

#  config:
#    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students
    username: springbootmicroservices
    password: springbootmicroservices
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

# ---------------------------------------------------------
#spring:
#  application:
#    name: students
#  config:
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:posgresql://localhost:5432/students
#    username: username
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hiberante.dialect.PostgreSQLDialect