# Read configuration from config server
spring:
  config:
#    this microservice does not fail to start if configuration does not exist on config-server
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery