# Read configuration from config server
spring:
  config:
#    it does not fail to start if the config does not exist
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery